[web]
host='0.0.0.0'
port=8000
allowed_origins = ["http://localhost:5173"]
show_docs = true

[redis]
enabled = false
host = 'localhost'
password = 'pwd'
port = 6379
expire_time = 600 # 10 minutes

[database]
url = 'sqlite:///db.sqlite3'
echo = false

[mqtt]
host = 'mqtt.host'
port = 1883
username = 'loon'
password = 'pwd'
log_data = false

[jwt]
secret = 'secret'
access_ttl = 86400 # 24h
ws_ttl = 45
